### ISSUE TITLE
How to train our own model？

### ISSUE THREAD

**Issue by A1069482459** [Calamari-OCR/calamari_models#7]
I want to train a set of my own handwriting model and want to know how to train。

**Comment by jbarth-ubhd** [comment]
Perhaps you could try ocr4all, which uses calamari 0.3x(?) including training feature

**Comment by chreul** [comment]
sorry, i somehow missed the initial question until now. you should start from [here](https://github.com/Calamari-OCR/calamari#training-of-a-model). if you run into problems, please open an issue in the calamari main repository with concrete information about the used data, the problems you ran into, etc.

btw: ocr4all is using calamari 1.0 since version 0.4 or so.

**Comment by A1069482459** [comment]
> Perhaps you could try ocr4all, which uses calamari 0.3x(?) including training feature

Thanks, I will try another day.

**Comment by A1069482459** [comment]
> sorry, i somehow missed the initial question until now. you should start from [here](https://github.com/Calamari-OCR/calamari#training-of-a-model). if you run into problems, please open an issue in the calamari main repository with concrete information about the used data, the problems you ran into, etc.
> 
> btw: ocr4all is using calamari 1.0 since version 0.4 or so.

Only the characters corresponding to a single picture can be trained here, but I want to train a set of thesaurus models belonging to a specific industry, what should I do?
